test = dict()
test.setdefault("course", [])
test.setdefault("professor", [])
test.setdefault("hours", [])
test.setdefault("isset", [])
print(test)
test["course"].append("COMPRO1")
test["course"].append("COMPRO2")
test["course"].append("COMPRO3")
print(test)
print(test["course"][1])
